server:
  port: 8080

spring:
  application:
    name: homepage-backend
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.163.com
    port: 465
    username: insipidknight@163.com
    password: ${hp.mail.password}

  datasource:
    url: ${hp.db.url}
    username: ${hp.db.username}
    password: ${hp.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  upload:
    path: homepage/images
    url-prefix: /uploads
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
